
//line cmd/gensym/gensym.go:63
package asm

type OpOperand int

const (
	OpPtrBC     OpOperand = (1<<17+iota)
	OpPortPtrC
	OpPtrDE
	OpPtrHL
	OpPtrIX
	OpPtrIY
	OpPtrImm8
	OpPtrImm16
	OpPtrSP
	OpRegA
	OpRegAF
	OpRegAFS
	OpRegB
	OpRegBC
	OpRegC
	OpRegD
	OpRegDE
	OpRegE
	OpRegH
	OpRegHL
	OpRegI
	OpRegIX
	OpRegIY
	OpRegL
	OpRegR
	OpRegSP
	OpFlag
	OpImm8
	OpOffset
	OpImm16
	OpReg
	OpInt
	OpString
)


type OpInfo struct {
	Name string
	Size int
	Operands []OpOperand
	OpCode []string
}

type OpCodeFunc func(operands ... byte) []byte

var Ops = []OpInfo {


OpInfo { Name: "ADC", Size: 1, OpCode: []string{"0x8E", }, Operands:[]OpOperand{OpRegA, OpPtrHL, } },
OpInfo { Name: "ADC", Size: 3, OpCode: []string{"0xDD", "0x8E", "0xXX", }, Operands:[]OpOperand{OpRegA, OpPtrIX, OpOffset, } },
OpInfo { Name: "ADC", Size: 3, OpCode: []string{"0xFD", "0x8E", "0xXX", }, Operands:[]OpOperand{OpRegA, OpPtrIY, OpOffset, } },
OpInfo { Name: "ADC", Size: 1, OpCode: []string{"0x88+rb", }, Operands:[]OpOperand{OpRegA, OpReg, } },
OpInfo { Name: "ADC", Size: 2, OpCode: []string{"0xCE", "0xXX", }, Operands:[]OpOperand{OpRegA, OpFlag, } },
OpInfo { Name: "ADC", Size: 2, OpCode: []string{"0xED", "0x4A", }, Operands:[]OpOperand{OpRegHL, OpRegBC, } },
OpInfo { Name: "ADC", Size: 2, OpCode: []string{"0xED", "0x5A", }, Operands:[]OpOperand{OpRegHL, OpRegDE, } },
OpInfo { Name: "ADC", Size: 2, OpCode: []string{"0xED", "0x6A", }, Operands:[]OpOperand{OpRegHL, OpRegHL, } },
OpInfo { Name: "ADC", Size: 2, OpCode: []string{"0xED", "0x7A", }, Operands:[]OpOperand{OpRegHL, OpRegSP, } },
OpInfo { Name: "ADD", Size: 1, OpCode: []string{"0x86", }, Operands:[]OpOperand{OpRegA, OpPtrHL, } },
OpInfo { Name: "ADD", Size: 3, OpCode: []string{"0xDD", "0x86", "0xXX", }, Operands:[]OpOperand{OpRegA, OpPtrIX, OpOffset, } },
OpInfo { Name: "ADD", Size: 3, OpCode: []string{"0xFD", "0x86", "0xXX", }, Operands:[]OpOperand{OpRegA, OpPtrIY, OpOffset, } },
OpInfo { Name: "ADD", Size: 1, OpCode: []string{"0x80+rb", }, Operands:[]OpOperand{OpRegA, OpReg, } },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xC6", "0xXX", }, Operands:[]OpOperand{OpRegA, OpFlag, } },
OpInfo { Name: "ADD", Size: 1, OpCode: []string{"0x09", }, Operands:[]OpOperand{OpRegHL, OpRegBC, } },
OpInfo { Name: "ADD", Size: 1, OpCode: []string{"0x19", }, Operands:[]OpOperand{OpRegHL, OpRegDE, } },
OpInfo { Name: "ADD", Size: 1, OpCode: []string{"0x29", }, Operands:[]OpOperand{OpRegHL, OpRegHL, } },
OpInfo { Name: "ADD", Size: 1, OpCode: []string{"0x39", }, Operands:[]OpOperand{OpRegHL, OpRegSP, } },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xDD", "0x09", }, Operands:[]OpOperand{OpRegIX, OpRegBC, } },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xDD", "0x19", }, Operands:[]OpOperand{OpRegIX, OpRegDE, } },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xDD", "0x29", }, Operands:[]OpOperand{OpRegIX, OpRegIX, } },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xDD", "0x39", }, Operands:[]OpOperand{OpRegIX, OpRegSP, } },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xFD", "0x09", }, Operands:[]OpOperand{OpRegIY, OpRegBC, } },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xFD", "0x19", }, Operands:[]OpOperand{OpRegIY, OpRegDE, } },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xFD", "0x29", }, Operands:[]OpOperand{OpRegIY, OpRegIY, } },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xFD", "0x39", }, Operands:[]OpOperand{OpRegIY, OpRegSP, } },
OpInfo { Name: "AND", Size: 1, OpCode: []string{"0xA6", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "AND", Size: 3, OpCode: []string{"0xDD", "0xA6", "0xXX", }, Operands:[]OpOperand{OpPtrIX, OpOffset, } },
OpInfo { Name: "AND", Size: 3, OpCode: []string{"0xFD", "0xA6", "0xXX", }, Operands:[]OpOperand{OpPtrIY, OpOffset, } },
OpInfo { Name: "AND", Size: 1, OpCode: []string{"0xA0+rb", }, Operands:[]OpOperand{OpReg, } },
OpInfo { Name: "AND", Size: 2, OpCode: []string{"0xE6", "0xXX", }, Operands:[]OpOperand{OpFlag, } },
OpInfo { Name: "BIT", Size: 2, OpCode: []string{"0xCB", "0x46+8*b", }, Operands:[]OpOperand{OpOffset, OpPtrHL, } },
OpInfo { Name: "BIT", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x46+8*b", }, Operands:[]OpOperand{OpOffset, OpPtrIX, OpOffset, } },
OpInfo { Name: "BIT", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x46+8*b", }, Operands:[]OpOperand{OpOffset, OpPtrIY, OpOffset, } },
OpInfo { Name: "BIT", Size: 2, OpCode: []string{"0xCB", "0x40+8*b+rb", }, Operands:[]OpOperand{OpOffset, OpReg, } },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xDC", "0xXX", "0xXX", }, Operands:[]OpOperand{OpRegC, OpImm16, } },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xFC", "0xXX", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm16, } },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xD4", "0xXX", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm16, } },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xCD", "0xXX", "0xXX", }, Operands:[]OpOperand{OpImm16, } },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xC4", "0xXX", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm16, } },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xF4", "0xXX", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm16, } },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xEC", "0xXX", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm16, } },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xE4", "0xXX", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm16, } },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xCC", "0xXX", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm16, } },
OpInfo { Name: "CCF", Size: 1, OpCode: []string{"0x3F", }, Operands:[]OpOperand{} },
OpInfo { Name: "CP", Size: 1, OpCode: []string{"0xBE", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "CP", Size: 3, OpCode: []string{"0xDD", "0xBE", "0xXX", }, Operands:[]OpOperand{OpPtrIX, OpOffset, } },
OpInfo { Name: "CP", Size: 3, OpCode: []string{"0xFD", "0xBE", "0xXX", }, Operands:[]OpOperand{OpPtrIY, OpOffset, } },
OpInfo { Name: "CP", Size: 1, OpCode: []string{"0xB8+rb", }, Operands:[]OpOperand{OpReg, } },
OpInfo { Name: "CP", Size: 2, OpCode: []string{"0xFE", "0xXX", }, Operands:[]OpOperand{OpFlag, } },
OpInfo { Name: "CPD", Size: 2, OpCode: []string{"0xED", "0xA9", }, Operands:[]OpOperand{} },
OpInfo { Name: "CPDR", Size: 2, OpCode: []string{"0xED", "0xB9", }, Operands:[]OpOperand{} },
OpInfo { Name: "CPI", Size: 2, OpCode: []string{"0xED", "0xA1", }, Operands:[]OpOperand{} },
OpInfo { Name: "CPIR", Size: 2, OpCode: []string{"0xED", "0xB1", }, Operands:[]OpOperand{} },
OpInfo { Name: "CPL", Size: 1, OpCode: []string{"0x2F", }, Operands:[]OpOperand{} },
OpInfo { Name: "DAA", Size: 1, OpCode: []string{"0x27", }, Operands:[]OpOperand{} },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x35", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "DEC", Size: 3, OpCode: []string{"0xDD", "0x35", "0xXX", }, Operands:[]OpOperand{OpPtrIX, OpOffset, } },
OpInfo { Name: "DEC", Size: 3, OpCode: []string{"0xFD", "0x35", "0xXX", }, Operands:[]OpOperand{OpPtrIY, OpOffset, } },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x3D", }, Operands:[]OpOperand{OpRegA, } },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x05", }, Operands:[]OpOperand{OpRegB, } },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x0B", }, Operands:[]OpOperand{OpRegBC, } },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x0D", }, Operands:[]OpOperand{OpRegC, } },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x15", }, Operands:[]OpOperand{OpRegD, } },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x1B", }, Operands:[]OpOperand{OpRegDE, } },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x1D", }, Operands:[]OpOperand{OpRegE, } },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x25", }, Operands:[]OpOperand{OpRegH, } },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x2B", }, Operands:[]OpOperand{OpRegHL, } },
OpInfo { Name: "DEC", Size: 2, OpCode: []string{"0xDD", "0x2B", }, Operands:[]OpOperand{OpRegIX, } },
OpInfo { Name: "DEC", Size: 2, OpCode: []string{"0xFD", "0x2B", }, Operands:[]OpOperand{OpRegIY, } },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x2D", }, Operands:[]OpOperand{OpRegL, } },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x3B", }, Operands:[]OpOperand{OpRegSP, } },
OpInfo { Name: "DI", Size: 1, OpCode: []string{"0xF3", }, Operands:[]OpOperand{} },
OpInfo { Name: "DJNZ", Size: 2, OpCode: []string{"0x10", "0xXX", }, Operands:[]OpOperand{OpImm8, } },
OpInfo { Name: "EI", Size: 1, OpCode: []string{"0xFB", }, Operands:[]OpOperand{} },
OpInfo { Name: "EX", Size: 1, OpCode: []string{"0xE3", }, Operands:[]OpOperand{OpPtrSP, OpRegHL, } },
OpInfo { Name: "EX", Size: 2, OpCode: []string{"0xDD", "0xE3", }, Operands:[]OpOperand{OpPtrSP, OpRegIX, } },
OpInfo { Name: "EX", Size: 2, OpCode: []string{"0xFD", "0xE3", }, Operands:[]OpOperand{OpPtrSP, OpRegIY, } },
OpInfo { Name: "EX", Size: 1, OpCode: []string{"0x08", }, Operands:[]OpOperand{OpRegAF, OpRegAFS, } },
OpInfo { Name: "EX", Size: 1, OpCode: []string{"0xEB", }, Operands:[]OpOperand{OpRegDE, OpRegHL, } },
OpInfo { Name: "EXX", Size: 1, OpCode: []string{"0xD9", }, Operands:[]OpOperand{} },
OpInfo { Name: "HALT", Size: 1, OpCode: []string{"0x76", }, Operands:[]OpOperand{} },
OpInfo { Name: "IM", Size: 2, OpCode: []string{"0xED", "0x46", }, Operands:[]OpOperand{OpInt, } },
OpInfo { Name: "IM", Size: 2, OpCode: []string{"0xED", "0x56", }, Operands:[]OpOperand{OpInt, } },
OpInfo { Name: "IM", Size: 2, OpCode: []string{"0xED", "0x5E", }, Operands:[]OpOperand{OpInt, } },
OpInfo { Name: "IN", Size: 2, OpCode: []string{"0xED", "0x78", }, Operands:[]OpOperand{OpRegA, OpPortPtrC, } },
OpInfo { Name: "IN", Size: 2, OpCode: []string{"0xDB", "0xXX", }, Operands:[]OpOperand{OpRegA, OpPtrImm8, } },
OpInfo { Name: "IN", Size: 2, OpCode: []string{"0xED", "0x40", }, Operands:[]OpOperand{OpRegB, OpPortPtrC, } },
OpInfo { Name: "IN", Size: 2, OpCode: []string{"0xED", "0x48", }, Operands:[]OpOperand{OpRegC, OpPortPtrC, } },
OpInfo { Name: "IN", Size: 2, OpCode: []string{"0xED", "0x50", }, Operands:[]OpOperand{OpRegD, OpPortPtrC, } },
OpInfo { Name: "IN", Size: 2, OpCode: []string{"0xED", "0x58", }, Operands:[]OpOperand{OpRegE, OpPortPtrC, } },
OpInfo { Name: "IN", Size: 2, OpCode: []string{"0xED", "0x60", }, Operands:[]OpOperand{OpRegH, OpPortPtrC, } },
OpInfo { Name: "IN", Size: 2, OpCode: []string{"0xED", "0x68", }, Operands:[]OpOperand{OpRegL, OpPortPtrC, } },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x34", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "INC", Size: 3, OpCode: []string{"0xDD", "0x34", "0xXX", }, Operands:[]OpOperand{OpPtrIX, OpOffset, } },
OpInfo { Name: "INC", Size: 3, OpCode: []string{"0xFD", "0x34", "0xXX", }, Operands:[]OpOperand{OpPtrIY, OpOffset, } },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x3C", }, Operands:[]OpOperand{OpRegA, } },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x04", }, Operands:[]OpOperand{OpRegB, } },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x03", }, Operands:[]OpOperand{OpRegBC, } },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x0C", }, Operands:[]OpOperand{OpRegC, } },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x14", }, Operands:[]OpOperand{OpRegD, } },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x13", }, Operands:[]OpOperand{OpRegDE, } },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x1C", }, Operands:[]OpOperand{OpRegE, } },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x24", }, Operands:[]OpOperand{OpRegH, } },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x23", }, Operands:[]OpOperand{OpRegHL, } },
OpInfo { Name: "INC", Size: 2, OpCode: []string{"0xDD", "0x23", }, Operands:[]OpOperand{OpRegIX, } },
OpInfo { Name: "INC", Size: 2, OpCode: []string{"0xFD", "0x23", }, Operands:[]OpOperand{OpRegIY, } },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x2C", }, Operands:[]OpOperand{OpRegL, } },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x33", }, Operands:[]OpOperand{OpRegSP, } },
OpInfo { Name: "IND", Size: 2, OpCode: []string{"0xED", "0xAA", }, Operands:[]OpOperand{} },
OpInfo { Name: "INDR", Size: 2, OpCode: []string{"0xED", "0xBA", }, Operands:[]OpOperand{} },
OpInfo { Name: "INI", Size: 2, OpCode: []string{"0xED", "0xA2", }, Operands:[]OpOperand{} },
OpInfo { Name: "INIR", Size: 2, OpCode: []string{"0xED", "0xB2", }, Operands:[]OpOperand{} },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xC3", "0xXX", "0xXX", }, Operands:[]OpOperand{OpImm16, } },
OpInfo { Name: "JP", Size: 1, OpCode: []string{"0xE9", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "JP", Size: 2, OpCode: []string{"0xDD", "0xE9", }, Operands:[]OpOperand{OpPtrIX, } },
OpInfo { Name: "JP", Size: 2, OpCode: []string{"0xFD", "0xE9", }, Operands:[]OpOperand{OpPtrIY, } },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xDA", "0xXX", "0xXX", }, Operands:[]OpOperand{OpRegC, OpImm16, } },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xFA", "0xXX", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm16, } },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xD2", "0xXX", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm16, } },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xC2", "0xXX", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm16, } },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xF2", "0xXX", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm16, } },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xEA", "0xXX", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm16, } },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xE2", "0xXX", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm16, } },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xCA", "0xXX", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm16, } },
OpInfo { Name: "JR", Size: 2, OpCode: []string{"0x18", "0xXX", }, Operands:[]OpOperand{OpImm8, } },
OpInfo { Name: "JR", Size: 2, OpCode: []string{"0x38", "0xXX", }, Operands:[]OpOperand{OpRegC, OpImm8, } },
OpInfo { Name: "JR", Size: 2, OpCode: []string{"0x30", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm8, } },
OpInfo { Name: "JR", Size: 2, OpCode: []string{"0x20", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm8, } },
OpInfo { Name: "JR", Size: 2, OpCode: []string{"0x28", "0xXX", }, Operands:[]OpOperand{OpFlag, OpImm8, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x02", }, Operands:[]OpOperand{OpPtrBC, OpRegA, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x12", }, Operands:[]OpOperand{OpPtrDE, OpRegA, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x70+rb", }, Operands:[]OpOperand{OpPtrHL, OpReg, } },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0x36", "0xXX", }, Operands:[]OpOperand{OpPtrHL, OpFlag, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xDD", "0x70+rb", "0xXX", }, Operands:[]OpOperand{OpPtrIX, OpOffset, OpReg, } },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xDD", "0x36", "0xXX", "0xXX", }, Operands:[]OpOperand{OpPtrIX, OpOffset, OpFlag, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xFD", "0x70+rb", "0xXX", }, Operands:[]OpOperand{OpPtrIY, OpOffset, OpReg, } },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xFD", "0x36", "0xXX", "0xXX", }, Operands:[]OpOperand{OpPtrIY, OpOffset, OpFlag, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0x32", "0xXX", "0xXX", }, Operands:[]OpOperand{OpPtrImm16, OpRegA, } },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xED", "0x43", "0xXX", "0xXX", }, Operands:[]OpOperand{OpPtrImm16, OpRegBC, } },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xED", "0x53", "0xXX", "0xXX", }, Operands:[]OpOperand{OpPtrImm16, OpRegDE, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0x22", "0xXX", "0xXX", }, Operands:[]OpOperand{OpPtrImm16, OpRegHL, } },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xDD", "0x22", "0xXX", "0xXX", }, Operands:[]OpOperand{OpPtrImm16, OpRegIX, } },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xFD", "0x22", "0xXX", "0xXX", }, Operands:[]OpOperand{OpPtrImm16, OpRegIY, } },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xED", "0x73", "0xXX", "0xXX", }, Operands:[]OpOperand{OpPtrImm16, OpRegSP, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x0A", }, Operands:[]OpOperand{OpRegA, OpPtrBC, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x1A", }, Operands:[]OpOperand{OpRegA, OpPtrDE, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x7E", }, Operands:[]OpOperand{OpRegA, OpPtrHL, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xDD", "0x7E", "0xXX", }, Operands:[]OpOperand{OpRegA, OpPtrIX, OpOffset, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xFD", "0x7E", "0xXX", }, Operands:[]OpOperand{OpRegA, OpPtrIY, OpOffset, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0x3A", "0xXX", "0xXX", }, Operands:[]OpOperand{OpRegA, OpPtrImm16, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x78+rb", }, Operands:[]OpOperand{OpRegA, OpReg, } },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0xED", "0x57", }, Operands:[]OpOperand{OpRegA, OpRegI, } },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0x3E", "0xXX", }, Operands:[]OpOperand{OpRegA, OpFlag, } },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0xED", "0x5F", }, Operands:[]OpOperand{OpRegA, OpRegR, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x46", }, Operands:[]OpOperand{OpRegB, OpPtrHL, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xDD", "0x46", "0xXX", }, Operands:[]OpOperand{OpRegB, OpPtrIX, OpOffset, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xFD", "0x46", "0xXX", }, Operands:[]OpOperand{OpRegB, OpPtrIY, OpOffset, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x40+rb", }, Operands:[]OpOperand{OpRegB, OpReg, } },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0x06", "0xXX", }, Operands:[]OpOperand{OpRegB, OpFlag, } },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xED", "0x4B", "0xXX", "0xXX", }, Operands:[]OpOperand{OpRegBC, OpPtrImm16, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0x01", "0xXX", "0xXX", }, Operands:[]OpOperand{OpRegBC, OpImm16, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x4E", }, Operands:[]OpOperand{OpRegC, OpPtrHL, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xDD", "0x4E", "0xXX", }, Operands:[]OpOperand{OpRegC, OpPtrIX, OpOffset, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xFD", "0x4E", "0xXX", }, Operands:[]OpOperand{OpRegC, OpPtrIY, OpOffset, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x48+rb", }, Operands:[]OpOperand{OpRegC, OpReg, } },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0x0E", "0xXX", }, Operands:[]OpOperand{OpRegC, OpFlag, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x56", }, Operands:[]OpOperand{OpRegD, OpPtrHL, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xDD", "0x56", "0xXX", }, Operands:[]OpOperand{OpRegD, OpPtrIX, OpOffset, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xFD", "0x56", "0xXX", }, Operands:[]OpOperand{OpRegD, OpPtrIY, OpOffset, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x50+rb", }, Operands:[]OpOperand{OpRegD, OpReg, } },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0x16", "0xXX", }, Operands:[]OpOperand{OpRegD, OpFlag, } },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xED", "0x5B", "0xXX", "0xXX", }, Operands:[]OpOperand{OpRegDE, OpPtrImm16, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0x11", "0xXX", "0xXX", }, Operands:[]OpOperand{OpRegDE, OpImm16, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x5E", }, Operands:[]OpOperand{OpRegE, OpPtrHL, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xDD", "0x5E", "0xXX", }, Operands:[]OpOperand{OpRegE, OpPtrIX, OpOffset, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xFD", "0x5E", "0xXX", }, Operands:[]OpOperand{OpRegE, OpPtrIY, OpOffset, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x58+rb", }, Operands:[]OpOperand{OpRegE, OpReg, } },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0x1E", "0xXX", }, Operands:[]OpOperand{OpRegE, OpFlag, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x66", }, Operands:[]OpOperand{OpRegH, OpPtrHL, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xDD", "0x66", "0xXX", }, Operands:[]OpOperand{OpRegH, OpPtrIX, OpOffset, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xFD", "0x66", "0xXX", }, Operands:[]OpOperand{OpRegH, OpPtrIY, OpOffset, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x60+rb", }, Operands:[]OpOperand{OpRegH, OpReg, } },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0x26", "0xXX", }, Operands:[]OpOperand{OpRegH, OpFlag, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0x2A", "0xXX", "0xXX", }, Operands:[]OpOperand{OpRegHL, OpPtrImm16, } },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xED", "0x6B", "0xXX", "0xXX", }, Operands:[]OpOperand{OpRegHL, OpPtrImm16, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0x21", "0xXX", "0xXX", }, Operands:[]OpOperand{OpRegHL, OpImm16, } },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0xED", "0x47", }, Operands:[]OpOperand{OpRegI, OpRegA, } },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xDD", "0x2A", "0xXX", "0xXX", }, Operands:[]OpOperand{OpRegIX, OpPtrImm16, } },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xDD", "0x21", "0xXX", "0xXX", }, Operands:[]OpOperand{OpRegIX, OpImm16, } },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xFD", "0x2A", "0xXX", "0xXX", }, Operands:[]OpOperand{OpRegIY, OpPtrImm16, } },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xFD", "0x21", "0xXX", "0xXX", }, Operands:[]OpOperand{OpRegIY, OpImm16, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x6E", }, Operands:[]OpOperand{OpRegL, OpPtrHL, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xDD", "0x6E", "0xXX", }, Operands:[]OpOperand{OpRegL, OpPtrIX, OpOffset, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xFD", "0x6E", "0xXX", }, Operands:[]OpOperand{OpRegL, OpPtrIY, OpOffset, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x68+rb", }, Operands:[]OpOperand{OpRegL, OpReg, } },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0x2E", "0xXX", }, Operands:[]OpOperand{OpRegL, OpFlag, } },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0xED", "0x4F", }, Operands:[]OpOperand{OpRegR, OpRegA, } },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xED", "0x7B", "0xXX", "0xXX", }, Operands:[]OpOperand{OpRegSP, OpPtrImm16, } },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0xF9", }, Operands:[]OpOperand{OpRegSP, OpRegHL, } },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0xDD", "0xF9", }, Operands:[]OpOperand{OpRegSP, OpRegIX, } },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0xFD", "0xF9", }, Operands:[]OpOperand{OpRegSP, OpRegIY, } },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0x31", "0xXX", "0xXX", }, Operands:[]OpOperand{OpRegSP, OpImm16, } },
OpInfo { Name: "LDD", Size: 2, OpCode: []string{"0xED", "0xA8", }, Operands:[]OpOperand{} },
OpInfo { Name: "LDDR", Size: 2, OpCode: []string{"0xED", "0xB8", }, Operands:[]OpOperand{} },
OpInfo { Name: "LDI", Size: 2, OpCode: []string{"0xED", "0xA0", }, Operands:[]OpOperand{} },
OpInfo { Name: "LDIR", Size: 2, OpCode: []string{"0xED", "0xB0", }, Operands:[]OpOperand{} },
OpInfo { Name: "NEG", Size: 2, OpCode: []string{"0xED", "0x44", }, Operands:[]OpOperand{} },
OpInfo { Name: "NOP", Size: 1, OpCode: []string{"0x00", }, Operands:[]OpOperand{} },
OpInfo { Name: "OR", Size: 1, OpCode: []string{"0xB6", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "OR", Size: 3, OpCode: []string{"0xDD", "0xB6", "0xXX", }, Operands:[]OpOperand{OpPtrIX, OpOffset, } },
OpInfo { Name: "OR", Size: 3, OpCode: []string{"0xFD", "0xB6", "0xXX", }, Operands:[]OpOperand{OpPtrIY, OpOffset, } },
OpInfo { Name: "OR", Size: 1, OpCode: []string{"0xB0+rb", }, Operands:[]OpOperand{OpReg, } },
OpInfo { Name: "OR", Size: 2, OpCode: []string{"0xF6", "0xXX", }, Operands:[]OpOperand{OpFlag, } },
OpInfo { Name: "OTDR", Size: 2, OpCode: []string{"0xED", "0xBB", }, Operands:[]OpOperand{} },
OpInfo { Name: "OTIR", Size: 2, OpCode: []string{"0xED", "0xB3", }, Operands:[]OpOperand{} },
OpInfo { Name: "OUT", Size: 2, OpCode: []string{"0xED", "0x79", }, Operands:[]OpOperand{OpPortPtrC, OpRegA, } },
OpInfo { Name: "OUT", Size: 2, OpCode: []string{"0xED", "0x41", }, Operands:[]OpOperand{OpPortPtrC, OpRegB, } },
OpInfo { Name: "OUT", Size: 2, OpCode: []string{"0xED", "0x49", }, Operands:[]OpOperand{OpPortPtrC, OpRegC, } },
OpInfo { Name: "OUT", Size: 2, OpCode: []string{"0xED", "0x51", }, Operands:[]OpOperand{OpPortPtrC, OpRegD, } },
OpInfo { Name: "OUT", Size: 2, OpCode: []string{"0xED", "0x59", }, Operands:[]OpOperand{OpPortPtrC, OpRegE, } },
OpInfo { Name: "OUT", Size: 2, OpCode: []string{"0xED", "0x61", }, Operands:[]OpOperand{OpPortPtrC, OpRegH, } },
OpInfo { Name: "OUT", Size: 2, OpCode: []string{"0xED", "0x69", }, Operands:[]OpOperand{OpPortPtrC, OpRegL, } },
OpInfo { Name: "OUT", Size: 2, OpCode: []string{"0xD3", "0xXX", }, Operands:[]OpOperand{OpPtrImm8, OpRegA, } },
OpInfo { Name: "OUTD", Size: 2, OpCode: []string{"0xED", "0xAB", }, Operands:[]OpOperand{} },
OpInfo { Name: "OUTI", Size: 2, OpCode: []string{"0xED", "0xA3", }, Operands:[]OpOperand{} },
OpInfo { Name: "POP", Size: 1, OpCode: []string{"0xF1", }, Operands:[]OpOperand{OpRegAF, } },
OpInfo { Name: "POP", Size: 1, OpCode: []string{"0xC1", }, Operands:[]OpOperand{OpRegBC, } },
OpInfo { Name: "POP", Size: 1, OpCode: []string{"0xD1", }, Operands:[]OpOperand{OpRegDE, } },
OpInfo { Name: "POP", Size: 1, OpCode: []string{"0xE1", }, Operands:[]OpOperand{OpRegHL, } },
OpInfo { Name: "POP", Size: 2, OpCode: []string{"0xDD", "0xE1", }, Operands:[]OpOperand{OpRegIX, } },
OpInfo { Name: "POP", Size: 2, OpCode: []string{"0xFD", "0xE1", }, Operands:[]OpOperand{OpRegIY, } },
OpInfo { Name: "PUSH", Size: 1, OpCode: []string{"0xF5", }, Operands:[]OpOperand{OpRegAF, } },
OpInfo { Name: "PUSH", Size: 1, OpCode: []string{"0xC5", }, Operands:[]OpOperand{OpRegBC, } },
OpInfo { Name: "PUSH", Size: 1, OpCode: []string{"0xD5", }, Operands:[]OpOperand{OpRegDE, } },
OpInfo { Name: "PUSH", Size: 1, OpCode: []string{"0xE5", }, Operands:[]OpOperand{OpRegHL, } },
OpInfo { Name: "PUSH", Size: 2, OpCode: []string{"0xDD", "0xE5", }, Operands:[]OpOperand{OpRegIX, } },
OpInfo { Name: "PUSH", Size: 2, OpCode: []string{"0xFD", "0xE5", }, Operands:[]OpOperand{OpRegIY, } },
OpInfo { Name: "RES", Size: 2, OpCode: []string{"0xCB", "0x86+8*b", }, Operands:[]OpOperand{OpOffset, OpPtrHL, } },
OpInfo { Name: "RES", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x86+8*b", }, Operands:[]OpOperand{OpOffset, OpPtrIX, OpOffset, } },
OpInfo { Name: "RES", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x86+8*b", }, Operands:[]OpOperand{OpOffset, OpPtrIY, OpOffset, } },
OpInfo { Name: "RES", Size: 2, OpCode: []string{"0xCB", "0x80+8*b+rb", }, Operands:[]OpOperand{OpOffset, OpReg, } },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xC9", }, Operands:[]OpOperand{} },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xD8", }, Operands:[]OpOperand{OpRegC, } },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xF8", }, Operands:[]OpOperand{OpFlag, } },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xD0", }, Operands:[]OpOperand{OpFlag, } },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xC0", }, Operands:[]OpOperand{OpFlag, } },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xF0", }, Operands:[]OpOperand{OpFlag, } },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xE8", }, Operands:[]OpOperand{OpFlag, } },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xE0", }, Operands:[]OpOperand{OpFlag, } },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xC8", }, Operands:[]OpOperand{OpFlag, } },
OpInfo { Name: "RETI", Size: 2, OpCode: []string{"0xED", "0x4D", }, Operands:[]OpOperand{} },
OpInfo { Name: "RETN", Size: 2, OpCode: []string{"0xED", "0x45", }, Operands:[]OpOperand{} },
OpInfo { Name: "RL", Size: 2, OpCode: []string{"0xCB", "0x16", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "RL", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x16", }, Operands:[]OpOperand{OpPtrIX, OpOffset, } },
OpInfo { Name: "RL", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x16", }, Operands:[]OpOperand{OpPtrIY, OpOffset, } },
OpInfo { Name: "RL", Size: 2, OpCode: []string{"0xCB", "0x10+rb", }, Operands:[]OpOperand{OpReg, } },
OpInfo { Name: "RLA", Size: 1, OpCode: []string{"0x17", }, Operands:[]OpOperand{} },
OpInfo { Name: "RLC", Size: 2, OpCode: []string{"0xCB", "0x06", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "RLC", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x06", }, Operands:[]OpOperand{OpPtrIX, OpOffset, } },
OpInfo { Name: "RLC", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x06", }, Operands:[]OpOperand{OpPtrIY, OpOffset, } },
OpInfo { Name: "RLC", Size: 2, OpCode: []string{"0xCB", "0x00+rb", }, Operands:[]OpOperand{OpReg, } },
OpInfo { Name: "RLCA", Size: 1, OpCode: []string{"0x07", }, Operands:[]OpOperand{} },
OpInfo { Name: "RLD", Size: 2, OpCode: []string{"0xED", "0x6F", }, Operands:[]OpOperand{} },
OpInfo { Name: "RR", Size: 2, OpCode: []string{"0xCB", "0x1E", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "RR", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x1E", }, Operands:[]OpOperand{OpPtrIX, OpOffset, } },
OpInfo { Name: "RR", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x1E", }, Operands:[]OpOperand{OpPtrIY, OpOffset, } },
OpInfo { Name: "RR", Size: 2, OpCode: []string{"0xCB", "0x18+rb", }, Operands:[]OpOperand{OpReg, } },
OpInfo { Name: "RRA", Size: 1, OpCode: []string{"0x1F", }, Operands:[]OpOperand{} },
OpInfo { Name: "RRC", Size: 2, OpCode: []string{"0xCB", "0x0E", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "RRC", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x0E", }, Operands:[]OpOperand{OpPtrIX, OpOffset, } },
OpInfo { Name: "RRC", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x0E", }, Operands:[]OpOperand{OpPtrIY, OpOffset, } },
OpInfo { Name: "RRC", Size: 2, OpCode: []string{"0xCB", "0x08+rb", }, Operands:[]OpOperand{OpReg, } },
OpInfo { Name: "RRCA", Size: 1, OpCode: []string{"0x0F", }, Operands:[]OpOperand{} },
OpInfo { Name: "RRD", Size: 2, OpCode: []string{"0xED", "0x67", }, Operands:[]OpOperand{} },
OpInfo { Name: "RST", Size: 1, OpCode: []string{"0xC7", }, Operands:[]OpOperand{OpInt, } },
OpInfo { Name: "RST", Size: 1, OpCode: []string{"0xCF", }, Operands:[]OpOperand{OpInt, } },
OpInfo { Name: "RST", Size: 1, OpCode: []string{"0xD7", }, Operands:[]OpOperand{OpInt, } },
OpInfo { Name: "RST", Size: 1, OpCode: []string{"0xDF", }, Operands:[]OpOperand{OpInt, } },
OpInfo { Name: "RST", Size: 1, OpCode: []string{"0xE7", }, Operands:[]OpOperand{OpInt, } },
OpInfo { Name: "RST", Size: 1, OpCode: []string{"0xEF", }, Operands:[]OpOperand{OpInt, } },
OpInfo { Name: "RST", Size: 1, OpCode: []string{"0xF7", }, Operands:[]OpOperand{OpInt, } },
OpInfo { Name: "RST", Size: 1, OpCode: []string{"0xFF", }, Operands:[]OpOperand{OpInt, } },
OpInfo { Name: "SBC", Size: 1, OpCode: []string{"0x9E", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "SBC", Size: 3, OpCode: []string{"0xDD", "0x9E", "0xXX", }, Operands:[]OpOperand{OpRegA, OpPtrIX, OpOffset, } },
OpInfo { Name: "SBC", Size: 3, OpCode: []string{"0xFD", "0x9E", "0xXX", }, Operands:[]OpOperand{OpRegA, OpPtrIY, OpOffset, } },
OpInfo { Name: "SBC", Size: 2, OpCode: []string{"0xDE", "0xXX", }, Operands:[]OpOperand{OpRegA, OpFlag, } },
OpInfo { Name: "SBC", Size: 1, OpCode: []string{"0x98+rb", }, Operands:[]OpOperand{OpReg, } },
OpInfo { Name: "SBC", Size: 2, OpCode: []string{"0xED", "0x42", }, Operands:[]OpOperand{OpRegHL, OpRegBC, } },
OpInfo { Name: "SBC", Size: 2, OpCode: []string{"0xED", "0x52", }, Operands:[]OpOperand{OpRegHL, OpRegDE, } },
OpInfo { Name: "SBC", Size: 2, OpCode: []string{"0xED", "0x62", }, Operands:[]OpOperand{OpRegHL, OpRegHL, } },
OpInfo { Name: "SBC", Size: 2, OpCode: []string{"0xED", "0x72", }, Operands:[]OpOperand{OpRegHL, OpRegSP, } },
OpInfo { Name: "SCF", Size: 1, OpCode: []string{"0x37", }, Operands:[]OpOperand{} },
OpInfo { Name: "SET", Size: 2, OpCode: []string{"0xCB", "0xC6+8*b", }, Operands:[]OpOperand{OpOffset, OpPtrHL, } },
OpInfo { Name: "SET", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0xC6+8*b", }, Operands:[]OpOperand{OpOffset, OpPtrIX, OpOffset, } },
OpInfo { Name: "SET", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0xC6+8*b", }, Operands:[]OpOperand{OpOffset, OpPtrIY, OpOffset, } },
OpInfo { Name: "SET", Size: 2, OpCode: []string{"0xCB", "0xC0+8*b+rb", }, Operands:[]OpOperand{OpOffset, OpReg, } },
OpInfo { Name: "SLA", Size: 2, OpCode: []string{"0xCB", "0x26", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "SLA", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x26", }, Operands:[]OpOperand{OpPtrIX, OpOffset, } },
OpInfo { Name: "SLA", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x26", }, Operands:[]OpOperand{OpPtrIY, OpOffset, } },
OpInfo { Name: "SLA", Size: 2, OpCode: []string{"0xCB", "0x20+rb", }, Operands:[]OpOperand{OpReg, } },
OpInfo { Name: "SLL", Size: 2, OpCode: []string{"0xCB", "0x36", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "SLL", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x36", }, Operands:[]OpOperand{OpPtrIX, OpOffset, } },
OpInfo { Name: "SLL", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x36", }, Operands:[]OpOperand{OpPtrIY, OpOffset, } },
OpInfo { Name: "SLL", Size: 2, OpCode: []string{"0xCB", "0x30+rb", }, Operands:[]OpOperand{OpReg, } },
OpInfo { Name: "SRA", Size: 2, OpCode: []string{"0xCB", "0x2E", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "SRA", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x2E", }, Operands:[]OpOperand{OpPtrIX, OpOffset, } },
OpInfo { Name: "SRA", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x2E", }, Operands:[]OpOperand{OpPtrIY, OpOffset, } },
OpInfo { Name: "SRA", Size: 2, OpCode: []string{"0xCB", "0x28+rb", }, Operands:[]OpOperand{OpReg, } },
OpInfo { Name: "SRL", Size: 2, OpCode: []string{"0xCB", "0x3E", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "SRL", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x3E", }, Operands:[]OpOperand{OpPtrIX, OpOffset, } },
OpInfo { Name: "SRL", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x3E", }, Operands:[]OpOperand{OpPtrIY, OpOffset, } },
OpInfo { Name: "SRL", Size: 2, OpCode: []string{"0xCB", "0x38+rb", }, Operands:[]OpOperand{OpReg, } },
OpInfo { Name: "SUB", Size: 1, OpCode: []string{"0x96", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "SUB", Size: 3, OpCode: []string{"0xDD", "0x96", "0xXX", }, Operands:[]OpOperand{OpPtrIX, OpOffset, } },
OpInfo { Name: "SUB", Size: 3, OpCode: []string{"0xFD", "0x96", "0xXX", }, Operands:[]OpOperand{OpPtrIY, OpOffset, } },
OpInfo { Name: "SUB", Size: 1, OpCode: []string{"0x90+rb", }, Operands:[]OpOperand{OpReg, } },
OpInfo { Name: "SUB", Size: 2, OpCode: []string{"0xD6", "0xXX", }, Operands:[]OpOperand{OpFlag, } },
OpInfo { Name: "XOR", Size: 1, OpCode: []string{"0xAE", }, Operands:[]OpOperand{OpPtrHL, } },
OpInfo { Name: "XOR", Size: 3, OpCode: []string{"0xDD", "0xAE", "0xXX", }, Operands:[]OpOperand{OpPtrIX, OpOffset, } },
OpInfo { Name: "XOR", Size: 3, OpCode: []string{"0xFD", "0xAE", "0xXX", }, Operands:[]OpOperand{OpPtrIY, OpOffset, } },
OpInfo { Name: "XOR", Size: 1, OpCode: []string{"0xA8+rb", }, Operands:[]OpOperand{OpReg, } },
OpInfo { Name: "XOR", Size: 2, OpCode: []string{"0xEE", "0xXX", }, Operands:[]OpOperand{OpFlag, } },

}

