
//line cmd/gensym/gensym.go:64
package asm

type OpInfo struct {
	Name string
	Size int
	Operands []OperandKind
	OpCode []string
}

type Asm interface {
	Assemble(bytes []byte)
}

type OpCodeFunc func(asm Asm) error

var Ops = []OpInfo {


OpInfo { Name: "ADC", Size: 1, OpCode: []string{"0x8E", }, Operands:[]OperandKind{KindReg8, KindPtrReg16} },
OpInfo { Name: "ADC", Size: 3, OpCode: []string{"0xDD", "0x8E", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "ADC", Size: 3, OpCode: []string{"0xFD", "0x8E", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "ADC", Size: 1, OpCode: []string{"0x88+rb", }, Operands:[]OperandKind{KindReg8, KindReg8} },
OpInfo { Name: "ADC", Size: 2, OpCode: []string{"0xCE", "0xXX", }, Operands:[]OperandKind{KindReg8, KindImm8} },
OpInfo { Name: "ADC", Size: 2, OpCode: []string{"0xED", "0x4A", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "ADC", Size: 2, OpCode: []string{"0xED", "0x5A", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "ADC", Size: 2, OpCode: []string{"0xED", "0x6A", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "ADC", Size: 2, OpCode: []string{"0xED", "0x7A", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "ADD", Size: 1, OpCode: []string{"0x86", }, Operands:[]OperandKind{KindReg8, KindPtrReg16} },
OpInfo { Name: "ADD", Size: 3, OpCode: []string{"0xDD", "0x86", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "ADD", Size: 3, OpCode: []string{"0xFD", "0x86", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "ADD", Size: 1, OpCode: []string{"0x80+rb", }, Operands:[]OperandKind{KindReg8, KindReg8} },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xC6", "0xXX", }, Operands:[]OperandKind{KindReg8, KindImm8} },
OpInfo { Name: "ADD", Size: 1, OpCode: []string{"0x09", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "ADD", Size: 1, OpCode: []string{"0x19", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "ADD", Size: 1, OpCode: []string{"0x29", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "ADD", Size: 1, OpCode: []string{"0x39", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xDD", "0x09", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xDD", "0x19", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xDD", "0x29", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xDD", "0x39", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xFD", "0x09", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xFD", "0x19", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xFD", "0x29", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "ADD", Size: 2, OpCode: []string{"0xFD", "0x39", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "AND", Size: 1, OpCode: []string{"0xA6", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "AND", Size: 3, OpCode: []string{"0xDD", "0xA6", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "AND", Size: 3, OpCode: []string{"0xFD", "0xA6", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "AND", Size: 1, OpCode: []string{"0xA0+rb", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "AND", Size: 2, OpCode: []string{"0xE6", "0xXX", }, Operands:[]OperandKind{KindImm8} },
OpInfo { Name: "BIT", Size: 2, OpCode: []string{"0xCB", "0x46+8*b", }, Operands:[]OperandKind{KindOff8, KindPtrReg16} },
OpInfo { Name: "BIT", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x46+8*b", }, Operands:[]OperandKind{KindOff8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "BIT", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x46+8*b", }, Operands:[]OperandKind{KindOff8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "BIT", Size: 2, OpCode: []string{"0xCB", "0x40+8*b+rb", }, Operands:[]OperandKind{KindOff8, KindReg8} },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xDC", "0xXX", "0xXX", }, Operands:[]OperandKind{KindReg8, KindImm16} },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xFC", "0xXX", "0xXX", }, Operands:[]OperandKind{KindImm16} },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xD4", "0xXX", "0xXX", }, Operands:[]OperandKind{KindFla, KindImm16} },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xCD", "0xXX", "0xXX", }, Operands:[]OperandKind{KindImm16} },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xC4", "0xXX", "0xXX", }, Operands:[]OperandKind{KindFla, KindImm16} },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xF4", "0xXX", "0xXX", }, Operands:[]OperandKind{KindImm16} },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xEC", "0xXX", "0xXX", }, Operands:[]OperandKind{KindFla, KindImm16} },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xE4", "0xXX", "0xXX", }, Operands:[]OperandKind{KindFla, KindImm16} },
OpInfo { Name: "CALL", Size: 3, OpCode: []string{"0xCC", "0xXX", "0xXX", }, Operands:[]OperandKind{KindFla, KindImm16} },
OpInfo { Name: "CCF", Size: 1, OpCode: []string{"0x3F", }, Operands:[]OperandKind{} },
OpInfo { Name: "CP", Size: 1, OpCode: []string{"0xBE", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "CP", Size: 3, OpCode: []string{"0xDD", "0xBE", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "CP", Size: 3, OpCode: []string{"0xFD", "0xBE", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "CP", Size: 1, OpCode: []string{"0xB8+rb", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "CP", Size: 2, OpCode: []string{"0xFE", "0xXX", }, Operands:[]OperandKind{KindImm8} },
OpInfo { Name: "CPD", Size: 2, OpCode: []string{"0xED", "0xA9", }, Operands:[]OperandKind{} },
OpInfo { Name: "CPDR", Size: 2, OpCode: []string{"0xED", "0xB9", }, Operands:[]OperandKind{} },
OpInfo { Name: "CPI", Size: 2, OpCode: []string{"0xED", "0xA1", }, Operands:[]OperandKind{} },
OpInfo { Name: "CPIR", Size: 2, OpCode: []string{"0xED", "0xB1", }, Operands:[]OperandKind{} },
OpInfo { Name: "CPL", Size: 1, OpCode: []string{"0x2F", }, Operands:[]OperandKind{} },
OpInfo { Name: "DAA", Size: 1, OpCode: []string{"0x27", }, Operands:[]OperandKind{} },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x35", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "DEC", Size: 3, OpCode: []string{"0xDD", "0x35", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "DEC", Size: 3, OpCode: []string{"0xFD", "0x35", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x3D", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x05", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x0B", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x0D", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x15", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x1B", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x1D", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x25", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x2B", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "DEC", Size: 2, OpCode: []string{"0xDD", "0x2B", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "DEC", Size: 2, OpCode: []string{"0xFD", "0x2B", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x2D", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "DEC", Size: 1, OpCode: []string{"0x3B", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "DI", Size: 1, OpCode: []string{"0xF3", }, Operands:[]OperandKind{} },
OpInfo { Name: "DJNZ", Size: 2, OpCode: []string{"0x10", "0xXX", }, Operands:[]OperandKind{KindImm8} },
OpInfo { Name: "EI", Size: 1, OpCode: []string{"0xFB", }, Operands:[]OperandKind{} },
OpInfo { Name: "EX", Size: 1, OpCode: []string{"0xE3", }, Operands:[]OperandKind{KindPtrReg16, KindReg16} },
OpInfo { Name: "EX", Size: 2, OpCode: []string{"0xDD", "0xE3", }, Operands:[]OperandKind{KindPtrReg16, KindReg16} },
OpInfo { Name: "EX", Size: 2, OpCode: []string{"0xFD", "0xE3", }, Operands:[]OperandKind{KindPtrReg16, KindReg16} },
OpInfo { Name: "EX", Size: 1, OpCode: []string{"0x08", }, Operands:[]OperandKind{KindReg16, KindRegSpc} },
OpInfo { Name: "EX", Size: 1, OpCode: []string{"0xEB", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "EXX", Size: 1, OpCode: []string{"0xD9", }, Operands:[]OperandKind{} },
OpInfo { Name: "HALT", Size: 1, OpCode: []string{"0x76", }, Operands:[]OperandKind{} },
OpInfo { Name: "IM", Size: 2, OpCode: []string{"0xED", "0x46", }, Operands:[]OperandKind{KindInt} },
OpInfo { Name: "IM", Size: 2, OpCode: []string{"0xED", "0x56", }, Operands:[]OperandKind{KindInt} },
OpInfo { Name: "IM", Size: 2, OpCode: []string{"0xED", "0x5E", }, Operands:[]OperandKind{KindInt} },
OpInfo { Name: "IN", Size: 2, OpCode: []string{"0xED", "0x78", }, Operands:[]OperandKind{KindReg8, KindPtrReg8} },
OpInfo { Name: "IN", Size: 2, OpCode: []string{"0xDB", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrImm8} },
OpInfo { Name: "IN", Size: 2, OpCode: []string{"0xED", "0x40", }, Operands:[]OperandKind{KindReg8, KindPtrReg8} },
OpInfo { Name: "IN", Size: 2, OpCode: []string{"0xED", "0x48", }, Operands:[]OperandKind{KindReg8, KindPtrReg8} },
OpInfo { Name: "IN", Size: 2, OpCode: []string{"0xED", "0x50", }, Operands:[]OperandKind{KindReg8, KindPtrReg8} },
OpInfo { Name: "IN", Size: 2, OpCode: []string{"0xED", "0x58", }, Operands:[]OperandKind{KindReg8, KindPtrReg8} },
OpInfo { Name: "IN", Size: 2, OpCode: []string{"0xED", "0x60", }, Operands:[]OperandKind{KindReg8, KindPtrReg8} },
OpInfo { Name: "IN", Size: 2, OpCode: []string{"0xED", "0x68", }, Operands:[]OperandKind{KindReg8, KindPtrReg8} },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x34", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "INC", Size: 3, OpCode: []string{"0xDD", "0x34", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "INC", Size: 3, OpCode: []string{"0xFD", "0x34", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x3C", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x04", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x03", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x0C", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x14", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x13", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x1C", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x24", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x23", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "INC", Size: 2, OpCode: []string{"0xDD", "0x23", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "INC", Size: 2, OpCode: []string{"0xFD", "0x23", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x2C", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "INC", Size: 1, OpCode: []string{"0x33", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "IND", Size: 2, OpCode: []string{"0xED", "0xAA", }, Operands:[]OperandKind{} },
OpInfo { Name: "INDR", Size: 2, OpCode: []string{"0xED", "0xBA", }, Operands:[]OperandKind{} },
OpInfo { Name: "INI", Size: 2, OpCode: []string{"0xED", "0xA2", }, Operands:[]OperandKind{} },
OpInfo { Name: "INIR", Size: 2, OpCode: []string{"0xED", "0xB2", }, Operands:[]OperandKind{} },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xC3", "0xXX", "0xXX", }, Operands:[]OperandKind{KindImm16} },
OpInfo { Name: "JP", Size: 1, OpCode: []string{"0xE9", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "JP", Size: 2, OpCode: []string{"0xDD", "0xE9", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "JP", Size: 2, OpCode: []string{"0xFD", "0xE9", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xDA", "0xXX", "0xXX", }, Operands:[]OperandKind{KindFla, KindImm16} },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xFA", "0xXX", "0xXX", }, Operands:[]OperandKind{KindFla, KindImm16} },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xD2", "0xXX", "0xXX", }, Operands:[]OperandKind{KindFla, KindImm16} },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xC2", "0xXX", "0xXX", }, Operands:[]OperandKind{KindFla, KindImm16} },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xF2", "0xXX", "0xXX", }, Operands:[]OperandKind{KindFla, KindImm16} },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xEA", "0xXX", "0xXX", }, Operands:[]OperandKind{KindFla, KindImm16} },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xE2", "0xXX", "0xXX", }, Operands:[]OperandKind{KindFla, KindImm16} },
OpInfo { Name: "JP", Size: 3, OpCode: []string{"0xCA", "0xXX", "0xXX", }, Operands:[]OperandKind{KindImm16} },
OpInfo { Name: "JR", Size: 2, OpCode: []string{"0x18", "0xXX", }, Operands:[]OperandKind{KindImm8} },
OpInfo { Name: "JR", Size: 2, OpCode: []string{"0x38", "0xXX", }, Operands:[]OperandKind{KindFla, KindImm8} },
OpInfo { Name: "JR", Size: 2, OpCode: []string{"0x30", "0xXX", }, Operands:[]OperandKind{KindFla, KindImm8} },
OpInfo { Name: "JR", Size: 2, OpCode: []string{"0x20", "0xXX", }, Operands:[]OperandKind{KindFla, KindImm8} },
OpInfo { Name: "JR", Size: 2, OpCode: []string{"0x28", "0xXX", }, Operands:[]OperandKind{KindImm8} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x02", }, Operands:[]OperandKind{KindPtrReg16, KindReg8} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x12", }, Operands:[]OperandKind{KindPtrReg16, KindReg8} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x70+rb", }, Operands:[]OperandKind{KindPtrReg16, KindReg8} },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0x36", "0xXX", }, Operands:[]OperandKind{KindPtrReg16, KindImm8} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xDD", "0x70+rb", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8, KindReg8} },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xDD", "0x36", "0xXX", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8, KindImm8} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xFD", "0x70+rb", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8, KindReg8} },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xFD", "0x36", "0xXX", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8, KindImm8} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0x32", "0xXX", "0xXX", }, Operands:[]OperandKind{KindPtrImm16, KindReg8} },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xED", "0x43", "0xXX", "0xXX", }, Operands:[]OperandKind{KindPtrImm16, KindReg16} },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xED", "0x53", "0xXX", "0xXX", }, Operands:[]OperandKind{KindPtrImm16, KindReg16} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0x22", "0xXX", "0xXX", }, Operands:[]OperandKind{KindPtrImm16, KindReg16} },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xDD", "0x22", "0xXX", "0xXX", }, Operands:[]OperandKind{KindPtrImm16, KindReg16} },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xFD", "0x22", "0xXX", "0xXX", }, Operands:[]OperandKind{KindPtrImm16, KindReg16} },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xED", "0x73", "0xXX", "0xXX", }, Operands:[]OperandKind{KindPtrImm16, KindReg16} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x0A", }, Operands:[]OperandKind{KindReg8, KindPtrReg16} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x1A", }, Operands:[]OperandKind{KindReg8, KindPtrReg16} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x7E", }, Operands:[]OperandKind{KindReg8, KindPtrReg16} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xDD", "0x7E", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xFD", "0x7E", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0x3A", "0xXX", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrImm16} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x78+rb", }, Operands:[]OperandKind{KindReg8, KindReg8} },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0xED", "0x57", }, Operands:[]OperandKind{KindReg8, KindRegSpc} },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0x3E", "0xXX", }, Operands:[]OperandKind{KindReg8, KindImm8} },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0xED", "0x5F", }, Operands:[]OperandKind{KindReg8, KindRegSpc} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x46", }, Operands:[]OperandKind{KindReg8, KindPtrReg16} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xDD", "0x46", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xFD", "0x46", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x40+rb", }, Operands:[]OperandKind{KindReg8, KindReg8} },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0x06", "0xXX", }, Operands:[]OperandKind{KindReg8, KindImm8} },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xED", "0x4B", "0xXX", "0xXX", }, Operands:[]OperandKind{KindReg16, KindPtrImm16} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0x01", "0xXX", "0xXX", }, Operands:[]OperandKind{KindReg16, KindImm16} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x4E", }, Operands:[]OperandKind{KindReg8, KindPtrReg16} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xDD", "0x4E", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xFD", "0x4E", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x48+rb", }, Operands:[]OperandKind{KindReg8, KindReg8} },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0x0E", "0xXX", }, Operands:[]OperandKind{KindReg8, KindImm8} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x56", }, Operands:[]OperandKind{KindReg8, KindPtrReg16} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xDD", "0x56", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xFD", "0x56", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x50+rb", }, Operands:[]OperandKind{KindReg8, KindReg8} },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0x16", "0xXX", }, Operands:[]OperandKind{KindReg8, KindImm8} },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xED", "0x5B", "0xXX", "0xXX", }, Operands:[]OperandKind{KindReg16, KindPtrImm16} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0x11", "0xXX", "0xXX", }, Operands:[]OperandKind{KindReg16, KindImm16} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x5E", }, Operands:[]OperandKind{KindReg8, KindPtrReg16} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xDD", "0x5E", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xFD", "0x5E", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x58+rb", }, Operands:[]OperandKind{KindReg8, KindReg8} },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0x1E", "0xXX", }, Operands:[]OperandKind{KindReg8, KindImm8} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x66", }, Operands:[]OperandKind{KindReg8, KindPtrReg16} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xDD", "0x66", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xFD", "0x66", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x60+rb", }, Operands:[]OperandKind{KindReg8, KindReg8} },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0x26", "0xXX", }, Operands:[]OperandKind{KindReg8, KindImm8} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0x2A", "0xXX", "0xXX", }, Operands:[]OperandKind{KindReg16, KindPtrImm16} },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xED", "0x6B", "0xXX", "0xXX", }, Operands:[]OperandKind{KindReg16, KindPtrImm16} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0x21", "0xXX", "0xXX", }, Operands:[]OperandKind{KindReg16, KindImm16} },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0xED", "0x47", }, Operands:[]OperandKind{KindRegSpc, KindReg8} },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xDD", "0x2A", "0xXX", "0xXX", }, Operands:[]OperandKind{KindReg16, KindPtrImm16} },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xDD", "0x21", "0xXX", "0xXX", }, Operands:[]OperandKind{KindReg16, KindImm16} },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xFD", "0x2A", "0xXX", "0xXX", }, Operands:[]OperandKind{KindReg16, KindPtrImm16} },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xFD", "0x21", "0xXX", "0xXX", }, Operands:[]OperandKind{KindReg16, KindImm16} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x6E", }, Operands:[]OperandKind{KindReg8, KindPtrReg16} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xDD", "0x6E", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0xFD", "0x6E", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0x68+rb", }, Operands:[]OperandKind{KindReg8, KindReg8} },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0x2E", "0xXX", }, Operands:[]OperandKind{KindReg8, KindImm8} },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0xED", "0x4F", }, Operands:[]OperandKind{KindRegSpc, KindReg8} },
OpInfo { Name: "LD", Size: 4, OpCode: []string{"0xED", "0x7B", "0xXX", "0xXX", }, Operands:[]OperandKind{KindReg16, KindPtrImm16} },
OpInfo { Name: "LD", Size: 1, OpCode: []string{"0xF9", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0xDD", "0xF9", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "LD", Size: 2, OpCode: []string{"0xFD", "0xF9", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "LD", Size: 3, OpCode: []string{"0x31", "0xXX", "0xXX", }, Operands:[]OperandKind{KindReg16, KindImm16} },
OpInfo { Name: "LDD", Size: 2, OpCode: []string{"0xED", "0xA8", }, Operands:[]OperandKind{} },
OpInfo { Name: "LDDR", Size: 2, OpCode: []string{"0xED", "0xB8", }, Operands:[]OperandKind{} },
OpInfo { Name: "LDI", Size: 2, OpCode: []string{"0xED", "0xA0", }, Operands:[]OperandKind{} },
OpInfo { Name: "LDIR", Size: 2, OpCode: []string{"0xED", "0xB0", }, Operands:[]OperandKind{} },
OpInfo { Name: "NEG", Size: 2, OpCode: []string{"0xED", "0x44", }, Operands:[]OperandKind{} },
OpInfo { Name: "NOP", Size: 1, OpCode: []string{"0x00", }, Operands:[]OperandKind{} },
OpInfo { Name: "OR", Size: 1, OpCode: []string{"0xB6", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "OR", Size: 3, OpCode: []string{"0xDD", "0xB6", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "OR", Size: 3, OpCode: []string{"0xFD", "0xB6", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "OR", Size: 1, OpCode: []string{"0xB0+rb", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "OR", Size: 2, OpCode: []string{"0xF6", "0xXX", }, Operands:[]OperandKind{KindImm8} },
OpInfo { Name: "OTDR", Size: 2, OpCode: []string{"0xED", "0xBB", }, Operands:[]OperandKind{} },
OpInfo { Name: "OTIR", Size: 2, OpCode: []string{"0xED", "0xB3", }, Operands:[]OperandKind{} },
OpInfo { Name: "OUT", Size: 2, OpCode: []string{"0xED", "0x79", }, Operands:[]OperandKind{KindPtrReg8, KindReg8} },
OpInfo { Name: "OUT", Size: 2, OpCode: []string{"0xED", "0x41", }, Operands:[]OperandKind{KindPtrReg8, KindReg8} },
OpInfo { Name: "OUT", Size: 2, OpCode: []string{"0xED", "0x49", }, Operands:[]OperandKind{KindPtrReg8, KindReg8} },
OpInfo { Name: "OUT", Size: 2, OpCode: []string{"0xED", "0x51", }, Operands:[]OperandKind{KindPtrReg8, KindReg8} },
OpInfo { Name: "OUT", Size: 2, OpCode: []string{"0xED", "0x59", }, Operands:[]OperandKind{KindPtrReg8, KindReg8} },
OpInfo { Name: "OUT", Size: 2, OpCode: []string{"0xED", "0x61", }, Operands:[]OperandKind{KindPtrReg8, KindReg8} },
OpInfo { Name: "OUT", Size: 2, OpCode: []string{"0xED", "0x69", }, Operands:[]OperandKind{KindPtrReg8, KindReg8} },
OpInfo { Name: "OUT", Size: 2, OpCode: []string{"0xD3", "0xXX", }, Operands:[]OperandKind{KindPtrImm8, KindReg8} },
OpInfo { Name: "OUTD", Size: 2, OpCode: []string{"0xED", "0xAB", }, Operands:[]OperandKind{} },
OpInfo { Name: "OUTI", Size: 2, OpCode: []string{"0xED", "0xA3", }, Operands:[]OperandKind{} },
OpInfo { Name: "POP", Size: 1, OpCode: []string{"0xF1", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "POP", Size: 1, OpCode: []string{"0xC1", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "POP", Size: 1, OpCode: []string{"0xD1", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "POP", Size: 1, OpCode: []string{"0xE1", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "POP", Size: 2, OpCode: []string{"0xDD", "0xE1", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "POP", Size: 2, OpCode: []string{"0xFD", "0xE1", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "PUSH", Size: 1, OpCode: []string{"0xF5", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "PUSH", Size: 1, OpCode: []string{"0xC5", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "PUSH", Size: 1, OpCode: []string{"0xD5", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "PUSH", Size: 1, OpCode: []string{"0xE5", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "PUSH", Size: 2, OpCode: []string{"0xDD", "0xE5", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "PUSH", Size: 2, OpCode: []string{"0xFD", "0xE5", }, Operands:[]OperandKind{KindReg16} },
OpInfo { Name: "RES", Size: 2, OpCode: []string{"0xCB", "0x86+8*b", }, Operands:[]OperandKind{KindOff8, KindPtrReg16} },
OpInfo { Name: "RES", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x86+8*b", }, Operands:[]OperandKind{KindOff8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "RES", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x86+8*b", }, Operands:[]OperandKind{KindOff8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "RES", Size: 2, OpCode: []string{"0xCB", "0x80+8*b+rb", }, Operands:[]OperandKind{KindOff8, KindReg8} },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xC9", }, Operands:[]OperandKind{} },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xD8", }, Operands:[]OperandKind{KindFla} },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xF8", }, Operands:[]OperandKind{KindFla} },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xD0", }, Operands:[]OperandKind{KindFla} },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xC0", }, Operands:[]OperandKind{KindFla} },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xF0", }, Operands:[]OperandKind{KindFla} },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xE8", }, Operands:[]OperandKind{KindFla} },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xE0", }, Operands:[]OperandKind{KindFla} },
OpInfo { Name: "RET", Size: 1, OpCode: []string{"0xC8", }, Operands:[]OperandKind{} },
OpInfo { Name: "RETI", Size: 2, OpCode: []string{"0xED", "0x4D", }, Operands:[]OperandKind{} },
OpInfo { Name: "RETN", Size: 2, OpCode: []string{"0xED", "0x45", }, Operands:[]OperandKind{} },
OpInfo { Name: "RL", Size: 2, OpCode: []string{"0xCB", "0x16", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "RL", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x16", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "RL", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x16", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "RL", Size: 2, OpCode: []string{"0xCB", "0x10+rb", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "RLA", Size: 1, OpCode: []string{"0x17", }, Operands:[]OperandKind{} },
OpInfo { Name: "RLC", Size: 2, OpCode: []string{"0xCB", "0x06", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "RLC", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x06", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "RLC", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x06", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "RLC", Size: 2, OpCode: []string{"0xCB", "0x00+rb", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "RLCA", Size: 1, OpCode: []string{"0x07", }, Operands:[]OperandKind{} },
OpInfo { Name: "RLD", Size: 2, OpCode: []string{"0xED", "0x6F", }, Operands:[]OperandKind{} },
OpInfo { Name: "RR", Size: 2, OpCode: []string{"0xCB", "0x1E", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "RR", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x1E", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "RR", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x1E", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "RR", Size: 2, OpCode: []string{"0xCB", "0x18+rb", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "RRA", Size: 1, OpCode: []string{"0x1F", }, Operands:[]OperandKind{} },
OpInfo { Name: "RRC", Size: 2, OpCode: []string{"0xCB", "0x0E", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "RRC", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x0E", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "RRC", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x0E", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "RRC", Size: 2, OpCode: []string{"0xCB", "0x08+rb", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "RRCA", Size: 1, OpCode: []string{"0x0F", }, Operands:[]OperandKind{} },
OpInfo { Name: "RRD", Size: 2, OpCode: []string{"0xED", "0x67", }, Operands:[]OperandKind{} },
OpInfo { Name: "RST", Size: 1, OpCode: []string{"0xC7", }, Operands:[]OperandKind{KindInt} },
OpInfo { Name: "RST", Size: 1, OpCode: []string{"0xCF", }, Operands:[]OperandKind{KindInt} },
OpInfo { Name: "RST", Size: 1, OpCode: []string{"0xD7", }, Operands:[]OperandKind{KindInt} },
OpInfo { Name: "RST", Size: 1, OpCode: []string{"0xDF", }, Operands:[]OperandKind{KindInt} },
OpInfo { Name: "RST", Size: 1, OpCode: []string{"0xE7", }, Operands:[]OperandKind{KindInt} },
OpInfo { Name: "RST", Size: 1, OpCode: []string{"0xEF", }, Operands:[]OperandKind{KindInt} },
OpInfo { Name: "RST", Size: 1, OpCode: []string{"0xF7", }, Operands:[]OperandKind{KindInt} },
OpInfo { Name: "RST", Size: 1, OpCode: []string{"0xFF", }, Operands:[]OperandKind{KindInt} },
OpInfo { Name: "SBC", Size: 1, OpCode: []string{"0x9E", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "SBC", Size: 3, OpCode: []string{"0xDD", "0x9E", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "SBC", Size: 3, OpCode: []string{"0xFD", "0x9E", "0xXX", }, Operands:[]OperandKind{KindReg8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "SBC", Size: 2, OpCode: []string{"0xDE", "0xXX", }, Operands:[]OperandKind{KindReg8, KindImm8} },
OpInfo { Name: "SBC", Size: 1, OpCode: []string{"0x98+rb", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "SBC", Size: 2, OpCode: []string{"0xED", "0x42", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "SBC", Size: 2, OpCode: []string{"0xED", "0x52", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "SBC", Size: 2, OpCode: []string{"0xED", "0x62", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "SBC", Size: 2, OpCode: []string{"0xED", "0x72", }, Operands:[]OperandKind{KindReg16, KindReg16} },
OpInfo { Name: "SCF", Size: 1, OpCode: []string{"0x37", }, Operands:[]OperandKind{} },
OpInfo { Name: "SET", Size: 2, OpCode: []string{"0xCB", "0xC6+8*b", }, Operands:[]OperandKind{KindOff8, KindPtrReg16} },
OpInfo { Name: "SET", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0xC6+8*b", }, Operands:[]OperandKind{KindOff8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "SET", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0xC6+8*b", }, Operands:[]OperandKind{KindOff8, KindPtrRegIdx, KindOff8} },
OpInfo { Name: "SET", Size: 2, OpCode: []string{"0xCB", "0xC0+8*b+rb", }, Operands:[]OperandKind{KindOff8, KindReg8} },
OpInfo { Name: "SLA", Size: 2, OpCode: []string{"0xCB", "0x26", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "SLA", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x26", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "SLA", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x26", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "SLA", Size: 2, OpCode: []string{"0xCB", "0x20+rb", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "SLL", Size: 2, OpCode: []string{"0xCB", "0x36", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "SLL", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x36", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "SLL", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x36", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "SLL", Size: 2, OpCode: []string{"0xCB", "0x30+rb", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "SRA", Size: 2, OpCode: []string{"0xCB", "0x2E", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "SRA", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x2E", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "SRA", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x2E", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "SRA", Size: 2, OpCode: []string{"0xCB", "0x28+rb", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "SRL", Size: 2, OpCode: []string{"0xCB", "0x3E", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "SRL", Size: 4, OpCode: []string{"0xDD", "0xCB", "0xXX", "0x3E", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "SRL", Size: 4, OpCode: []string{"0xFD", "0xCB", "0xXX", "0x3E", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "SRL", Size: 2, OpCode: []string{"0xCB", "0x38+rb", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "SUB", Size: 1, OpCode: []string{"0x96", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "SUB", Size: 3, OpCode: []string{"0xDD", "0x96", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "SUB", Size: 3, OpCode: []string{"0xFD", "0x96", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "SUB", Size: 1, OpCode: []string{"0x90+rb", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "SUB", Size: 2, OpCode: []string{"0xD6", "0xXX", }, Operands:[]OperandKind{KindImm8} },
OpInfo { Name: "XOR", Size: 1, OpCode: []string{"0xAE", }, Operands:[]OperandKind{KindPtrReg16} },
OpInfo { Name: "XOR", Size: 3, OpCode: []string{"0xDD", "0xAE", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "XOR", Size: 3, OpCode: []string{"0xFD", "0xAE", "0xXX", }, Operands:[]OperandKind{KindPtrRegIdx, KindOff8} },
OpInfo { Name: "XOR", Size: 1, OpCode: []string{"0xA8+rb", }, Operands:[]OperandKind{KindReg8} },
OpInfo { Name: "XOR", Size: 2, OpCode: []string{"0xEE", "0xXX", }, Operands:[]OperandKind{KindImm8} },

}

